# Drupal with MariaDB
#
# Access via "http://localhost:8080"
#   (or "http://$(docker-machine ip):8080" if using docker-machine)
#
# During initial Drupal setup,
# Database type: MariaDB
# Database name: drupal
# Database username: drupal
# Database password: drupal
# ADVANCED OPTIONS; Database host: mysql

version: '3.1'

volumes:
  drupal:
  db:

services:

  ingress:
    image: traefik:v2.5
    command: 
      - --entrypoints.web.address=:80
      - --entrypoints.web-secure.address=:443
      - --providers.docker
      - --providers.file.directory=/configuration/
      - --providers.file.watch=true
    ports:
      - "${INGRESS_HTTP_PORT}:80"
      - "${INGRESS_HTTPS_PORT}:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./ingress/configuration/:/configuration/
    labels:
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.port=${INGRESS_HTTPS_PORT}"
      - "traefik.http.routers.redirs.rule=hostregexp(`{host:.+}`)"
      - "traefik.http.routers.redirs.entrypoints=web"
      - "traefik.http.routers.redirs.middlewares=redirect-to-https"
    networks:
      default:
        aliases: 
        - ${DRUPAL_HOSTNAME}

  drupal:
    image: ktogias/civicrm-drupal:drupal10-3
    environment:
      DRUPAL_DB: ${DRUPAL_DB}
      DRUPAL_DB_USER: ${DRUPAL_DB_USER}
      DRUPAL_DB_PASSWORD: ${DRUPAL_DB_PASSWORD}
      DRUPAL_ADMIN_USERNAME: ${DRUPAL_ADMIN_USERNAME}
      DRUPAL_ADMIN_PASSWORD: ${DRUPAL_ADMIN_PASSWORD}
      DRUPAL_LOCALE: ${DRUPAL_LOCALE}
      DRUPAL_SITE_NAME: ${DRUPAL_SITE_NAME}
      CIVICRM_DB: ${CIVICRM_DB}
      CIVICRM_DB_USER: ${CIVICRM_DB_USER}
      CIVICRM_DB_PASSWORD: ${CIVICRM_DB_PASSWORD}
      CIVICRM_LANG: ${CIVICRM_LANG}
      CMS_BASE_URL: ${CMS_BASE_URL}
      TZ: ${TIMEZONE}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.drupal.rule=Host(`${DRUPAL_HOSTNAME}`)"
      - "traefik.http.routers.drupal.tls=true"
    volumes:
      - drupal:/opt/drupal
    restart: always
    depends_on:
      - db

  db:
    image: mariadb:11.2
    environment:
      MARIADB_RANDOM_ROOT_PASSWORD: "true"
      DRUPAL_DB: ${DRUPAL_DB}
      DRUPAL_DB_USER: ${DRUPAL_DB_USER}
      DRUPAL_DB_PASSWORD: ${DRUPAL_DB_PASSWORD}
      CIVICRM_DB: ${CIVICRM_DB}
      CIVICRM_DB_USER: ${CIVICRM_DB_USER}
      CIVICRM_DB_PASSWORD: ${CIVICRM_DB_PASSWORD}
      TZ: ${TIMEZONE}
    volumes:
      - db:/var/lib/mysql
      - ./db/init:/docker-entrypoint-initdb.d
    restart: always
    labels:
      - "traefik.enable=false"

  autoheal:
    restart: always
    image: willfarrell/autoheal:1.2.0
    environment:
      - AUTOHEAL_CONTAINER_LABEL=all
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - "traefik.enable=false"

  # mailhog:
  #   image: mailhog/mailhog:v1.0.1
  #   ports:
  #     - 1025:1025
  #     - 8025:8025
  #   labels:
  #     -"traefik.enable=false"

