# Drupal with MariaDB
#
# Access via "http://localhost:8080"
#   (or "http://$(docker-machine ip):8080" if using docker-machine)
#
# During initial Drupal setup,
# Database type: MariaDB
# Database name: drupal
# Database username: drupal
# Database password: drupal
# ADVANCED OPTIONS; Database host: mysql

version: '3.1'

volumes:
  drupal:
  db:

services:

  drupal:
    image: ktogias/civicrm-drupal:drupal10
    environment:
      DRUPAL_DB: ${DRUPAL_DB}
      DRUPAL_DB_USER: ${DRUPAL_DB_USER}
      DRUPAL_DB_PASSWORD: ${DRUPAL_DB_PASSWORD}
      DRUPAL_ADMIN_USERNAME: ${DRUPAL_ADMIN_USERNAME}
      DRUPAL_ADMIN_PASSWORD: ${DRUPAL_ADMIN_PASSWORD}
      DRUPAL_LOCALE: ${DRUPAL_LOCALE}
      DRUPAL_SITE_NAME: ${DRUPAL_SITE_NAME}
      CIVICRM_DB: ${CIVICRM_DB}
      CIVICRM_DB_USER: ${CIVICRM_DB_USER}
      CIVICRM_DB_PASSWORD: ${CIVICRM_DB_PASSWORD}
      CIVICRM_LANG: ${CIVICRM_LANG}
      CMS_BASE_URL: ${CMS_BASE_URL}

    ports:
      - 8080:80
    volumes:
      - drupal:/opt/drupal
    restart: always
    depends_on:
      - db

  db:
    image: mariadb:11.2
    #command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MARIADB_RANDOM_ROOT_PASSWORD: "true"
      DRUPAL_DB: ${DRUPAL_DB}
      DRUPAL_DB_USER: ${DRUPAL_DB_USER}
      DRUPAL_DB_PASSWORD: ${DRUPAL_DB_PASSWORD}
      CIVICRM_DB: ${CIVICRM_DB}
      CIVICRM_DB_USER: ${CIVICRM_DB_USER}
      CIVICRM_DB_PASSWORD: ${CIVICRM_DB_PASSWORD}
    volumes:
      - db:/var/lib/mysql
      - ./db/init:/docker-entrypoint-initdb.d
    restart: always

  mailhog:
    image: mailhog/mailhog:v1.0.1
    ports:
      - 1025:1025
      - 8025:8025

